### ISSUE TITLE
Error pop up when I switch M1 to M2

### ISSUE THREAD

**Issue by valeria9131** [movementlabsxyz/bug-tracking#22]
Error: [DecimalError] Invalid argument: undefined
    at i [as constructor] (https://razordex.xyz/assets/index-DqjM4xlg.js:530:29283)
    at Qe.dividedBy.Qe.div (https://razordex.xyz/assets/index-DqjM4xlg.js:530:4622)
    at ms (https://razordex.xyz/assets/index-DZc0q8Rq.js:94:908)
    at x9 (https://razordex.xyz/assets/index-DqjM4xlg.js:44:17094)
    at xE (https://razordex.xyz/assets/index-DqjM4xlg.js:46:3143)
    at _K (https://razordex.xyz/assets/index-DqjM4xlg.js:46:44880)
    at hK (https://razordex.xyz/assets/index-DqjM4xlg.js:46:39822)
    at Gme (https://razordex.xyz/assets/index-DqjM4xlg.js:46:39748)
    at Z2 (https://razordex.xyz/assets/index-DqjM4xlg.js:46:39598)
    at AE (https://razordex.xyz/assets/index-DqjM4xlg.js:46:35960)
    
![m2](https://github.com/movementlabsxyz/bug-tracking/assets/171065423/3658b996-c0c8-431f-9bef-e468b2fbf597)

┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-22) by [Unito](https://www.unito.io)

**Comment by valeria9131** [comment]
Solved.
